### GRPC save
GRPC localhost:8081/store.Store/Save

{
  "key": "timezone",
  "value": "Europe/Moscow"
}

### GRPC read
GRPC localhost:8081/store.Store/Read

{
  "key": "timezone"
}

### GRPC save ttl
GRPC localhost:8081/store.Store/Save

{
  "key": "with_ttl",
  "value": "10",
  "ttl": 10
}

### GRPC read ttl
GRPC localhost:8081/store.Store/Read

{
  "key": "with_ttl"
}

### GRPC List
GRPC localhost:8081/store.Store/List

### HTTP save
POST localhost:8080/api/store/timezone
Content-Type: application/json

{
  "value": "Europe/Moscow - 11"
}


### HTTP read
GET localhost:8080/api/store/timezone
Content-Type: application/json
